apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: customer-profile-database
spec:
  memory: 500Mi
  cpu: "0.4"
  storageClassName: default
  monitorStorageClassName: default
  storageSize: 1G
  pgConfig:
    dbname: customer-profile-database
    username: pgadmin
    appUser: pgappuser
